### ISSUE TITLE
Refatorar o código do GitHub Actions

### ISSUE THREAD

**Issue by THONWELLING** [THONWELLING/rest-with-spring-boot-java#2]
Modificar o código do Github Actions para entregar a integração contínua 

- Algo em minhas credenciais no Docker Hub não está funcionando corretamente.

**Comment by THONWELLING** [comment]
Descobrir oque está de errado com o Docker Hub pois está dando erro de autenticação mesmo com usuário e senha corretos.

**Comment by THONWELLING** [comment]
Código atual :

```

name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login In Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ******
          password: *******

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build Application JARthonwelling
        run: mvn clean package

      - name: Docker Composing Build
        run: docker compose build

      - name: Tag Docker Image
        run: docker tag Thonwelling/rest-with-spring-boot-java:latest Thonwelling/rest-with-spring-boot-java:1.0.0

      - name: Push Docker Image
        run: docker push Thonwelling/rest-with-spring-boot-java:1.0.0
```
